### PR TITLE
Feat: add landing page for oss

### PR DESCRIPTION
**Pull request by bethesque**
Screen Shot 2019-09-20 at 3 08 41 pm

### CODE REVIEW

**Comment by uglyog** [comment]
The trial period is 14 days now

**Comment by mefellows** [comment]
Do we need to link this from the main site somehow?

**Comment by bethesque** [comment]
🤷‍♀ I'm not sure where we'd put it. It doesn't belong with the links at the top of the page. Let's see if anyone actually uses it.

**Comment by mefellows** [comment]
Ah, sorry I was confusing this with a task that Rebecca mentioned in our meeting last week. This is to link from the logs - got it!

**Pull request merged**
